# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: selenium master  workflowon

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6,3.7, 3.8, 3.9, '3.10', '3.11']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: 安装依赖包
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pytest-cov 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name:  Generate coverage report 
      run: |
        coverage run --source selenium_project --parallel-mode -m pytest
        coverage combine
        coverage xml -i
        # pytest --cov=./ --cov-report=xml
      env:
        COVERAGE_RUN: True
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with: 
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml 
